[2024-07-03T00:26:57.108+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [queued]>
[2024-07-03T00:26:57.111+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [queued]>
[2024-07-03T00:26:57.112+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-03T00:26:57.116+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): insert_users> on 2024-07-02 20:40:00+00:00
[2024-07-03T00:26:57.117+0000] {standard_task_runner.py:57} INFO - Started process 232 to run task
[2024-07-03T00:26:57.119+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'insert_users', 'scheduled__2024-07-02T20:40:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp80hfn42f']
[2024-07-03T00:26:57.120+0000] {standard_task_runner.py:85} INFO - Job 301: Subtask insert_users
[2024-07-03T00:26:57.140+0000] {task_command.py:410} INFO - Running <TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [running]> on host e25ac14d8d5f
[2024-07-03T00:26:57.216+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='insert_users' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T20:40:00+00:00'
[2024-07-03T00:26:57.217+0000] {logging_mixin.py:149} INFO - Inserting data into users from /opt/airflow/generator/fake_users.json...
[2024-07-03T00:26:57.220+0000] {logging_mixin.py:149} INFO - Error inserting data into users: time zone "x90222" not recognized
LINE 3: Parkerport, ME 47398', '254-721-4634x90222')
                               ^
[2024-07-03T00:26:57.220+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-03T00:26:57.230+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=insert_users, execution_date=20240702T204000, start_date=20240703T002657, end_date=20240703T002657
[2024-07-03T00:26:57.268+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-03T00:26:57.283+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T00:48:26.884+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [queued]>
[2024-07-03T00:48:26.887+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [queued]>
[2024-07-03T00:48:26.887+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-03T00:48:26.891+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): insert_users> on 2024-07-02 20:40:00+00:00
[2024-07-03T00:48:26.893+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2024-07-03T00:48:26.894+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'insert_users', 'scheduled__2024-07-02T20:40:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp88zcn1o4']
[2024-07-03T00:48:26.895+0000] {standard_task_runner.py:85} INFO - Job 329: Subtask insert_users
[2024-07-03T00:48:26.916+0000] {task_command.py:410} INFO - Running <TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [running]> on host 9ea872201ce6
[2024-07-03T00:48:26.975+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='insert_users' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T20:40:00+00:00'
[2024-07-03T00:48:26.975+0000] {logging_mixin.py:149} INFO - Inserting data into users from /opt/airflow/generator/fake_users.json...
[2024-07-03T00:48:26.979+0000] {logging_mixin.py:149} INFO - Error inserting data into users: not all arguments converted during string formatting
[2024-07-03T00:48:26.980+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-03T00:48:26.989+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=insert_users, execution_date=20240702T204000, start_date=20240703T004826, end_date=20240703T004826
[2024-07-03T00:48:27.032+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-03T00:48:27.044+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T00:56:49.945+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [queued]>
[2024-07-03T00:56:49.948+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [queued]>
[2024-07-03T00:56:49.948+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-03T00:56:49.952+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): insert_users> on 2024-07-02 20:40:00+00:00
[2024-07-03T00:56:49.953+0000] {standard_task_runner.py:57} INFO - Started process 30 to run task
[2024-07-03T00:56:49.954+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'insert_users', 'scheduled__2024-07-02T20:40:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp4v38us20']
[2024-07-03T00:56:49.955+0000] {standard_task_runner.py:85} INFO - Job 342: Subtask insert_users
[2024-07-03T00:56:49.973+0000] {task_command.py:410} INFO - Running <TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T20:40:00+00:00 [running]> on host 6b9834f2e9cc
[2024-07-03T00:56:50.008+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='insert_users' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T20:40:00+00:00'
[2024-07-03T00:56:50.008+0000] {logging_mixin.py:149} INFO - Inserting data into users from /opt/airflow/generator/fake_users.json...
[2024-07-03T00:56:50.010+0000] {logging_mixin.py:149} INFO - Error inserting data into users: not all arguments converted during string formatting
[2024-07-03T00:56:50.010+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-03T00:56:50.014+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=insert_users, execution_date=20240702T204000, start_date=20240703T005649, end_date=20240703T005650
[2024-07-03T00:56:50.055+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-03T00:56:50.070+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
