[2024-07-03T00:26:11.706+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T13:10:00+00:00 [queued]>
[2024-07-03T00:26:11.709+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T13:10:00+00:00 [queued]>
[2024-07-03T00:26:11.709+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-03T00:26:11.713+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): insert_users> on 2024-07-02 13:10:00+00:00
[2024-07-03T00:26:11.715+0000] {standard_task_runner.py:57} INFO - Started process 150 to run task
[2024-07-03T00:26:11.716+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'insert_users', 'scheduled__2024-07-02T13:10:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp7wrp0yso']
[2024-07-03T00:26:11.717+0000] {standard_task_runner.py:85} INFO - Job 267: Subtask insert_users
[2024-07-03T00:26:11.735+0000] {task_command.py:410} INFO - Running <TaskInstance: ecomm_data_pipeline.insert_users scheduled__2024-07-02T13:10:00+00:00 [running]> on host e25ac14d8d5f
[2024-07-03T00:26:11.770+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='insert_users' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T13:10:00+00:00'
[2024-07-03T00:26:11.770+0000] {logging_mixin.py:149} INFO - Inserting data into users from /opt/airflow/generator/fake_users.json...
[2024-07-03T00:26:11.772+0000] {logging_mixin.py:149} INFO - Error inserting data into users: time zone "x563" not recognized
LINE 3: Grimesfort, CA 46980', '438.895.9222x563')
                               ^
[2024-07-03T00:26:11.773+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-03T00:26:11.777+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=insert_users, execution_date=20240702T131000, start_date=20240703T002611, end_date=20240703T002611
[2024-07-03T00:26:11.817+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-03T00:26:11.825+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
