[2024-07-06T21:46:20.268+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initialize_etl_environment.create_users_table manual__2024-07-06T21:46:15.684805+00:00 [queued]>
[2024-07-06T21:46:20.271+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initialize_etl_environment.create_users_table manual__2024-07-06T21:46:15.684805+00:00 [queued]>
[2024-07-06T21:46:20.271+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-06T21:46:20.275+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_users_table> on 2024-07-06 21:46:15.684805+00:00
[2024-07-06T21:46:20.277+0000] {standard_task_runner.py:57} INFO - Started process 3200 to run task
[2024-07-06T21:46:20.278+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'initialize_etl_environment', 'create_users_table', 'manual__2024-07-06T21:46:15.684805+00:00', '--job-id', '1048', '--raw', '--subdir', 'DAGS_FOLDER/etl_env_init.py', '--cfg-path', '/tmp/tmpvov74rhd']
[2024-07-06T21:46:20.279+0000] {standard_task_runner.py:85} INFO - Job 1048: Subtask create_users_table
[2024-07-06T21:46:20.298+0000] {task_command.py:410} INFO - Running <TaskInstance: initialize_etl_environment.create_users_table manual__2024-07-06T21:46:15.684805+00:00 [running]> on host c058add182a5
[2024-07-06T21:46:20.333+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='initialize_etl_environment' AIRFLOW_CTX_TASK_ID='create_users_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T21:46:15.684805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-06T21:46:15.684805+00:00'
[2024-07-06T21:46:20.334+0000] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS raw.users (
        user_id INT PRIMARY KEY,
        username VARCHAR(50),
        email VARCHAR(100),
        address VARCHAR(255),
        phone_number VARCHAR(255),
        created_at TIMESTAMP 
    );
        
    
[2024-07-06T21:46:20.337+0000] {base.py:73} INFO - Using connection ID 'company_dw' for task execution.
[2024-07-06T21:46:20.358+0000] {base.py:73} INFO - Using connection ID 'company_dw' for task execution.
[2024-07-06T21:46:20.360+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS raw.users (
        user_id INT PRIMARY KEY,
        username VARCHAR(50),
        email VARCHAR(100),
        address VARCHAR(255),
        phone_number VARCHAR(255),
        created_at TIMESTAMP 
    );
        
    , parameters: None
[2024-07-06T21:46:20.365+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=initialize_etl_environment, task_id=create_users_table, execution_date=20240706T214615, start_date=20240706T214620, end_date=20240706T214620
[2024-07-06T21:46:20.377+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-06T21:46:20.389+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
